name: Criar APK ROBO SGU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: "platform-tools platforms;android-35 build-tools;35.0.0"

      - name: Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Compilar APK
        run: buildozer android debug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: robo-sgu-apk
          path: bin/*.apk
