name: Criar APK ROBÔ SGU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython

      - name: Compilar APK
        run: |
          buildozer android debug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: robo-sgu-apk
          path: bin/*.apk
